name: Node.js CI/CD

on:
  push: # Trigger on push events to master branch
    branches: [ master ]

jobs:
  lint:  # Job to run code linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Run ESLint
        run: npm run lint

  test:  # Job to run tests
    runs-on: ubuntu-latest
    needs: lint  # This job depends on the successful completion of the lint job
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Run Tests
        run: npm run test

  build:  # Job to build the project
    runs-on: ubuntu-latest
    needs: [ lint, test ]  # This job depends on both lint and test jobs
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build

